import type { Handler } from '@netlify/functions';
import { db, schema } from '../../src/db';
import { eq } from 'drizzle-orm';
import { getUserId, setUserIdCookie } from '../../src/utils/auth';
import { generateFantasyName } from '../../src/utils/username';
// Actually, useUsername.ts had the generator on the frontend. I need to move it or re-implement it backend side.
// I will assume for this step that I need to inline it or create a utility. I'll inline a simple one for now and refactor if needed.


export const handler: Handler = async (event) => {
    const headers = {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*', // We might want to restrict this in production eventually, but keeping it open for now as per likely existing config
    };

    if (event.httpMethod !== 'POST') {
        return { statusCode: 405, headers, body: 'Method Not Allowed' };
    }

    try {
        // 1. Check for existing cookie
        const cookieUserId = getUserId(event);

        if (cookieUserId) {
            // Validate user exists
            const existingUser = await db.query.users.findFirst({
                where: eq(schema.users.id, cookieUserId),
            });

            if (existingUser) {
                return {
                    statusCode: 200,
                    headers,
                    body: JSON.stringify(existingUser),
                };
            }
            // If cookie exists but user not found (deleted?), treat as new user flow below
        }

        // 2. Check for legacy migration (legacy_id in body)
        const body = JSON.parse(event.body || '{}');
        const legacyId = body.legacy_id;

        if (legacyId) {
            // Check if this legacy ID is a valid user in our DB
            const legacyUser = await db.query.users.findFirst({
                where: eq(schema.users.id, legacyId),
            });

            if (legacyUser) {
                // Determine if we need to set the cookie (migration successful)
                return {
                    statusCode: 200,
                    headers: {
                        ...headers,
                        'Set-Cookie': setUserIdCookie(legacyUser.id),
                    },
                    body: JSON.stringify(legacyUser),
                };
            }
        }

        // 3. Create new user
        if (!body.timezone) {
            return {
                statusCode: 400,
                headers,
                body: JSON.stringify({ error: 'Timezone is required' }),
            };
        }

        const newDisplayName = generateFantasyName();
        // ID is auto-generated by DB (defaultRandom), but we need it to return it.
        // Drizzle schema has defaultRandom() for ID.
        // We can insert and return.

        const [newUser] = await db.insert(schema.users)
            .values({
                displayName: newDisplayName,
                timezone: body.timezone || null
            })
            .returning();

        return {
            statusCode: 201,
            headers: {
                ...headers,
                'Set-Cookie': setUserIdCookie(newUser.id),
            },
            body: JSON.stringify(newUser),
        };

    } catch (error) {
        console.error('Identity params error:', error);
        return {
            statusCode: 500,
            headers,
            body: JSON.stringify({ error: 'Internal server error' }),
        };
    }
};
